import { Project, Lead, Service, PricingPlan, FAQ, Feedback, ShowcaseItem, SiteSettings, Page, PageSection } from '@/lib/types/admin'

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Tech Startup Website',
    slug: 'tech-startup-website',
    category: 'Website',
    description: 'Modern landing page for a tech startup with interactive animations',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    services: ['UI Design', 'Development', 'SEO'],
    demoLink: 'https://example.com',
    status: 'published',
    showcase: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'E-commerce Platform',
    slug: 'ecommerce-platform',
    category: 'E-commerce',
    description: 'Full-featured e-commerce platform with payment integration',
    image: 'https://images.unsplash.com/photo-1460925895917-adf4e6b1b9b8?w=500&h=300&fit=crop',
    services: ['Full Stack Development', 'Payment Integration'],
    demoLink: 'https://example.com',
    status: 'published',
    showcase: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Mobile App Design',
    slug: 'mobile-app-design',
    category: 'Mobile',
    description: 'Cross-platform mobile app with intuitive UI',
    image: 'https://images.unsplash.com/photo-1512941691920-25bef676fbf7?w=500&h=300&fit=crop',
    services: ['UI Design', 'UX Design'],
    status: 'draft',
    showcase: false,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    email: 'nguyenvana@gmail.com',
    phone: '0912345678',
    service: 'Web Development',
    message: 'Tôi muốn tạo một website cho công ty của tôi',
    status: 'new',
    notes: '',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: false,
  },
  {
    id: '2',
    name: 'Trần Thị B',
    email: 'tranthib@gmail.com',
    phone: '0987654321',
    service: 'UI/UX Design',
    message: 'Cần thiết kế giao diện cho ứng dụng di động',
    status: 'processing',
    notes: 'Đang liên hệ khách hàng',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isRead: true,
  },
  {
    id: '3',
    name: 'Lê Văn C',
    email: 'levanc@gmail.com',
    phone: '0912123456',
    service: 'SEO Optimization',
    message: 'Muốn tối ưu hóa SEO cho website hiện tại',
    status: 'completed',
    notes: 'Đã hoàn thành và gửi báo cáo',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isRead: true,
  },
  {
    id: '4',
    name: 'Phạm Thị D',
    email: 'phamthid@gmail.com',
    phone: '0923456789',
    service: 'Brand Design',
    message: 'Cần thiết kế logo và nhận diện thương hiệu',
    status: 'new',
    notes: '',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    isRead: false,
  },
  {
    id: '5',
    name: 'Hoàng Văn E',
    email: 'hoangvane@gmail.com',
    phone: '0934567890',
    service: 'Content Writing',
    message: 'Cần viết nội dung cho website',
    status: 'new',
    notes: '',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000),
    isRead: false,
  },
]

export const mockServices: Service[] = [
  { id: '1', name: 'Web Development', description: 'Xây dựng website chuyên nghiệp', icon: '🌐', order: 1 },
  { id: '2', name: 'UI/UX Design', description: 'Thiết kế giao diện người dùng', icon: '🎨', order: 2 },
  { id: '3', name: 'Mobile App', description: 'Phát triển ứng dụng di động', icon: '📱', order: 3 },
  { id: '4', name: 'SEO Optimization', description: 'Tối ưu hóa công cụ tìm kiếm', icon: '🔍', order: 4 },
  { id: '5', name: 'Brand Design', description: 'Thiết kế nhận diện thương hiệu', icon: '💼', order: 5 },
]

export const mockPricingPlans: PricingPlan[] = [
  {
    id: '1',
    name: 'Starter',
    price: 5000000,
    contactForPrice: false,
    featured: false,
    features: ['3 trang web', 'Thiết kế cơ bản', 'Hỗ trợ 1 tháng'],
    order: 1,
  },
  {
    id: '2',
    name: 'Professional',
    price: 15000000,
    contactForPrice: false,
    featured: true,
    features: ['10 trang web', 'Thiết kế cao cấp', 'Hỗ trợ 6 tháng', 'SEO tối ưu'],
    order: 2,
  },
  {
    id: '3',
    name: 'Enterprise',
    // price: null,
    contactForPrice: true,
    featured: false,
    features: ['Không giới hạn trang', 'Thiết kế tùy chỉnh', 'Hỗ trợ liên tục', 'Tích hợp hệ thống'],
    order: 3,
  },
]

export const mockFAQs: FAQ[] = [
  { id: '1', question: 'Chi phí xây dựng website bao nhiêu?', answer: 'Giá bắt đầu từ 5 triệu đồng tùy theo yêu cầu', order: 1 },
  { id: '2', question: 'Thời gian xây dựng website là bao lâu?', answer: 'Thường từ 2-4 tuần tùy theo độ phức tạp', order: 2 },
  { id: '3', question: 'Bạn cung cấp dịch vụ hỗ trợ sau xây dựng không?', answer: 'Có, chúng tôi cung cấp dịch vụ hỗ trợ kỹ thuật', order: 3 },
]

export const mockFeedback: Feedback[] = [
  {
    id: '1',
    name: 'Trương Minh Huy',
    role: 'CEO',
    company: 'Tech Solutions',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user1',
    review: 'STARTECH đã giúp chúng tôi xây dựng một website tuyệt vời. Đội ngũ chuyên nghiệp và tận tâm.',
    rating: 5,
    visible: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Ngô Hải Yến',
    role: 'Marketing Manager',
    company: 'Digital Agency',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user2',
    review: 'Chất lượng thiết kế rất cao, giao hàng đúng hạn.',
    rating: 5,
    visible: true,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'Đoàn Thế Hùng',
    role: 'Founder',
    company: 'Startup Vietnam',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user3',
    review: 'Giá cả hợp lý và chất lượng dịch vụ tốt. Sẽ hợp tác lại lần tới.',
    rating: 4,
    visible: true,
    createdAt: new Date('2024-03-01'),
  },
]

export const mockShowcase: ShowcaseItem[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Tech Startup Website',
    link: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    category: 'Website',
    order: 1,
  },
  {
    id: '2',
    projectId: '2',
    title: 'E-commerce Platform',
    link: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-adf4e6b1b9b8?w=500&h=300&fit=crop',
    category: 'E-commerce',
    order: 2,
  },
]

export const mockSiteSettings: SiteSettings = {
  logo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=STARTECH',
  siteName: 'STARTECH',
  description: 'Công ty thiết kế web chuyên nghiệp',
  email: 'contact@startech.vn',
  phone: '+84 912 345 678',
  address: 'Hà Nội, Việt Nam',
  socialLinks: {
    facebook: 'https://facebook.com/startech',
    instagram: 'https://instagram.com/startech',
    linkedin: 'https://linkedin.com/company/startech',
    zalo: '0912345678',
  },
}

export const mockPages: Page[] = [
  {
    id: '1',
    title: 'Trang Chủ',
    slug: 'home',
    status: 'published',
    sections: [
      {
        id: 'sec1',
        type: 'heading',
        title: 'Chào mừng đến STARTECH',
        content: 'Chúng tôi tạo ra những trải nghiệm web tuyệt vời',
        order: 1,
      },
      {
        id: 'sec2',
        type: 'text',
        content: 'Với hơn 5 năm kinh nghiệm, STARTECH đã giúp hàng trăm doanh nghiệp thành công.',
        order: 2,
      },
    ],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    title: 'Về Chúng Tôi',
    slug: 'about',
    status: 'published',
    sections: [
      {
        id: 'sec3',
        type: 'heading',
        title: 'Về STARTECH',
        content: 'Công ty thiết kế web hàng đầu Việt Nam',
        order: 1,
      },
    ],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
]
